services:
  backend:
    build:
      context: ./backend
    image: baujuncos/tp2-backend:v1.0
    ports:
        - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=ladrillo753
      - DB_NAME=pbbv
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    image: baujuncos/tp2-frontend:v1.0
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: tp2_db
    environment:
      MYSQL_ROOT_PASSWORD: ladrillo753
      MYSQL_DATABASE: pbbv
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -pladrillo753 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 12
    networks:
      - app-network

volumes:
  mysqldata:

networks:
  app-network:
    driver: bridge

